export const templateData = [
  {
    id: 1,
    title: "Product Performance Dashboard",
    category: "product",
    description:
      "Comprehensive view of product sales, inventory, and performance metrics",
    thumbnail:
      "https://placehold.co/600x400/4338CA/white?text=Product+Dashboard",
    author: "Analytics Team",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    rating: 4.8,
    reviews: 124,
    usage: 3250,
    price: 0,
    tags: ["Sales", "Inventory", "Performance"],
    lastUpdated: "2025-03-15",
    featured: true,
    premium: false,
    new: false,
    chartTypes: ["bar", "line", "pie"],
    compatibility: ["Excel", "PDF", "API"],
    previewImages: [
      "https://placehold.co/800x500/4338CA/white?text=Product+Preview+1",
      "https://placehold.co/800x500/4338CA/white?text=Product+Preview+2",
    ],
  },
  {
    id: 2,
    title: "Inventory Health Monitor",
    category: "inventory",
    description:
      "Track stock levels, turnover rates, and reorder points with advanced forecasting",
    thumbnail:
      "https://placehold.co/600x400/047857/white?text=Inventory+Monitor",
    author: "Supply Chain Experts",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704e",
    rating: 4.6,
    reviews: 89,
    usage: 2180,
    price: 19.99,
    tags: ["Stock Levels", "Forecasting", "Alerts"],
    lastUpdated: "2025-03-10",
    featured: false,
    premium: true,
    new: false,
    chartTypes: ["gauge", "heatmap", "line"],
    compatibility: ["Excel", "PDF", "API", "CSV"],
    previewImages: [
      "https://placehold.co/800x500/047857/white?text=Inventory+Preview+1",
      "https://placehold.co/800x500/047857/white?text=Inventory+Preview+2",
    ],
  },
  {
    id: 3,
    title: "Customer Segmentation Analysis",
    category: "customers",
    description:
      "Segment customers by behavior, demographics, and purchase history",
    thumbnail:
      "https://placehold.co/600x400/7C3AED/white?text=Customer+Analysis",
    author: "CRM Solutions",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704f",
    rating: 4.9,
    reviews: 156,
    usage: 4120,
    price: 29.99,
    tags: ["Segmentation", "Behavior", "Loyalty"],
    lastUpdated: "2025-03-25",
    featured: true,
    premium: true,
    new: true,
    chartTypes: ["scatter", "pie", "radar"],
    compatibility: ["Excel", "PDF", "API", "Tableau"],
    previewImages: [
      "https://placehold.co/800x500/7C3AED/white?text=Customer+Preview+1",
      "https://placehold.co/800x500/7C3AED/white?text=Customer+Preview+2",
    ],
  },
  {
    id: 4,
    title: "Order Fulfillment Tracker",
    category: "order",
    description:
      "Monitor order processing, shipping times, and fulfillment efficiency",
    thumbnail: "https://placehold.co/600x400/F59E0B/white?text=Order+Tracker",
    author: "Logistics Pro",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704g",
    rating: 4.5,
    reviews: 78,
    usage: 1890,
    price: 0,
    tags: ["Fulfillment", "Shipping", "Processing"],
    lastUpdated: "2025-03-05",
    featured: false,
    premium: false,
    new: false,
    chartTypes: ["timeline", "bar", "heatmap"],
    compatibility: ["Excel", "PDF", "API"],
    previewImages: [
      "https://placehold.co/800x500/F59E0B/white?text=Order+Preview+1",
      "https://placehold.co/800x500/F59E0B/white?text=Order+Preview+2",
    ],
  },
  {
    id: 5,
    title: "Product Catalog Manager",
    category: "product",
    description:
      "Organize and analyze your product catalog with category performance insights",
    thumbnail: "https://placehold.co/600x400/4338CA/white?text=Catalog+Manager",
    author: "Product Analytics",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704h",
    rating: 4.3,
    reviews: 62,
    usage: 1450,
    price: 14.99,
    tags: ["Catalog", "Categories", "Attributes"],
    lastUpdated: "2025-02-28",
    featured: false,
    premium: true,
    new: false,
    chartTypes: ["treemap", "bar", "sunburst"],
    compatibility: ["Excel", "PDF", "API", "CSV"],
    previewImages: [
      "https://placehold.co/800x500/4338CA/white?text=Catalog+Preview+1",
      "https://placehold.co/800x500/4338CA/white?text=Catalog+Preview+2",
    ],
  },
  {
    id: 6,
    title: "Inventory Aging Analysis",
    category: "inventory",
    description:
      "Track inventory age, identify slow-moving items, and optimize stock levels",
    thumbnail: "https://placehold.co/600x400/047857/white?text=Inventory+Aging",
    author: "Inventory Optimization",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704i",
    rating: 4.7,
    reviews: 93,
    usage: 2560,
    price: 0,
    tags: ["Aging", "Slow-Moving", "Optimization"],
    lastUpdated: "2025-03-20",
    featured: true,
    premium: false,
    new: true,
    chartTypes: ["heatmap", "bar", "line"],
    compatibility: ["Excel", "PDF", "API"],
    previewImages: [
      "https://placehold.co/800x500/047857/white?text=Aging+Preview+1",
      "https://placehold.co/800x500/047857/white?text=Aging+Preview+2",
    ],
  },
  {
    id: 7,
    title: "Customer Lifetime Value Report",
    category: "customers",
    description:
      "Calculate and forecast customer lifetime value with predictive analytics",
    thumbnail: "https://placehold.co/600x400/7C3AED/white?text=CLV+Report",
    author: "Customer Insights",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704j",
    rating: 4.8,
    reviews: 112,
    usage: 3050,
    price: 24.99,
    tags: ["CLV", "Prediction", "Retention"],
    lastUpdated: "2025-03-18",
    featured: false,
    premium: true,
    new: false,
    chartTypes: ["line", "scatter", "bar"],
    compatibility: ["Excel", "PDF", "API", "PowerBI"],
    previewImages: [
      "https://placehold.co/800x500/7C3AED/white?text=CLV+Preview+1",
      "https://placehold.co/800x500/7C3AED/white?text=CLV+Preview+2",
    ],
  },
  {
    id: 8,
    title: "Order Anomaly Detection",
    category: "order",
    description:
      "Identify unusual order patterns and potential fraud with AI-powered analytics",
    thumbnail:
      "https://placehold.co/600x400/F59E0B/white?text=Anomaly+Detection",
    author: "Security Analytics",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704k",
    rating: 4.9,
    reviews: 87,
    usage: 1980,
    price: 39.99,
    tags: ["Anomaly", "Fraud", "AI"],
    lastUpdated: "2025-03-22",
    featured: true,
    premium: true,
    new: true,
    chartTypes: ["scatter", "heatmap", "line"],
    compatibility: ["Excel", "PDF", "API", "ML Integration"],
    previewImages: [
      "https://placehold.co/800x500/F59E0B/white?text=Anomaly+Preview+1",
      "https://placehold.co/800x500/F59E0B/white?text=Anomaly+Preview+2",
    ],
  },
  {
    id: 9,
    title: "Product Bundle Performance",
    category: "product",
    description:
      "Analyze the performance of product bundles and cross-sell opportunities",
    thumbnail: "https://placehold.co/600x400/4338CA/white?text=Bundle+Analysis",
    author: "Marketing Analytics",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704l",
    rating: 4.4,
    reviews: 56,
    usage: 1320,
    price: 0,
    tags: ["Bundles", "Cross-sell", "Upsell"],
    lastUpdated: "2025-03-08",
    featured: false,
    premium: false,
    new: false,
    chartTypes: ["network", "bar", "sankey"],
    compatibility: ["Excel", "PDF", "API"],
    previewImages: [
      "https://placehold.co/800x500/4338CA/white?text=Bundle+Preview+1",
      "https://placehold.co/800x500/4338CA/white?text=Bundle+Preview+2",
    ],
  },
  {
    id: 10,
    title: "Inventory Forecasting Suite",
    category: "inventory",
    description:
      "Predict future inventory needs with machine learning and seasonal analysis",
    thumbnail:
      "https://placehold.co/600x400/047857/white?text=Inventory+Forecast",
    author: "AI Forecasting",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704m",
    rating: 4.7,
    reviews: 103,
    usage: 2780,
    price: 49.99,
    tags: ["Forecasting", "ML", "Seasonal"],
    lastUpdated: "2025-03-27",
    featured: true,
    premium: true,
    new: true,
    chartTypes: ["line", "area", "prediction"],
    compatibility: ["Excel", "PDF", "API", "ML Integration"],
    previewImages: [
      "https://placehold.co/800x500/047857/white?text=Forecast+Preview+1",
      "https://placehold.co/800x500/047857/white?text=Forecast+Preview+2",
    ],
  },
  {
    id: 11,
    title: "Customer Churn Predictor",
    category: "customers",
    description:
      "Identify at-risk customers and implement retention strategies",
    thumbnail: "https://placehold.co/600x400/7C3AED/white?text=Churn+Predictor",
    author: "Retention Experts",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704n",
    rating: 4.8,
    reviews: 118,
    usage: 3150,
    price: 34.99,
    tags: ["Churn", "Retention", "Prediction"],
    lastUpdated: "2025-03-12",
    featured: false,
    premium: true,
    new: false,
    chartTypes: ["probability", "heatmap", "funnel"],
    compatibility: ["Excel", "PDF", "API", "CRM Integration"],
    previewImages: [
      "https://placehold.co/800x500/7C3AED/white?text=Churn+Preview+1",
      "https://placehold.co/800x500/7C3AED/white?text=Churn+Preview+2",
    ],
  },
  {
    id: 12,
    title: "Order-to-Cash Workflow",
    category: "order",
    description:
      "Track the complete order-to-cash process with financial insights",
    thumbnail: "https://placehold.co/600x400/F59E0B/white?text=Order-to-Cash",
    author: "Finance Analytics",
    authorAvatar: "https://i.pravatar.cc/150?u=a042581f4e29026704o",
    rating: 4.6,
    reviews: 72,
    usage: 1680,
    price: 29.99,
    tags: ["O2C", "Finance", "Workflow"],
    lastUpdated: "2025-03-14",
    featured: false,
    premium: true,
    new: false,
    chartTypes: ["sankey", "timeline", "bar"],
    compatibility: ["Excel", "PDF", "API", "ERP Integration"],
    previewImages: [
      "https://placehold.co/800x500/F59E0B/white?text=O2C+Preview+1",
      "https://placehold.co/800x500/F59E0B/white?text=O2C+Preview+2",
    ],
  },
];

// Featured collections
export const featuredCollections = [
  {
    id: 1,
    title: "E-commerce Essentials",
    description: "Must-have reports for online retailers",
    templates: [1, 3, 4, 8],
    thumbnail:
      "https://placehold.co/600x300/6366F1/white?text=E-commerce+Essentials",
  },
  {
    id: 2,
    title: "Supply Chain Optimization",
    description: "Streamline your inventory and logistics",
    templates: [2, 6, 10, 12],
    thumbnail:
      "https://placehold.co/600x300/10B981/white?text=Supply+Chain+Optimization",
  },
  {
    id: 3,
    title: "Customer Intelligence Suite",
    description: "Deep insights into customer behavior",
    templates: [3, 7, 11],
    thumbnail:
      "https://placehold.co/600x300/8B5CF6/white?text=Customer+Intelligence",
  },
];

// Subscription plans
export const subscriptionPlans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    features: [
      "Access to free templates",
      "Basic customization",
      "PDF export",
      "5 reports per month",
    ],
    recommended: false,
  },
  {
    id: "pro",
    name: "Pro",
    price: 19.99,
    features: [
      "Access to all templates",
      "Advanced customization",
      "All export formats",
      "Unlimited reports",
      "API access",
    ],
    recommended: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 49.99,
    features: [
      "Everything in Pro",
      "Custom template creation",
      "White labeling",
      "Priority support",
      "Team collaboration",
      "Advanced integrations",
    ],
    recommended: false,
  },
];
