export const governorateCodes = {
    "Al Anbar": "IQ.AN",
    "Al Muthanna Governorate": "IQ.MU",
    "Al Qādisīyah": "IQ.QD",
    "An Najaf": "IQ.NJ",
    Bābil: "IQ.BB",
    Baghdad: "IQ.BG",
    Basra: "IQ.BA",
    "Dhi Qar": "IQ.DQ",
    Diyālá: "IQ.DI",
    Duhok: "IQ.DH",
    Erbil: "IQ.ER",
    "Halabja Governorate": "IQ.HL",
    Karbalāʼ: "IQ.KR",
    Kirkuk: "IQ.KI",
    Maysan: "IQ.MI",
    Nineveh: "IQ.NI",
    "Salah ad Din": "IQ.SD",
    Sulaymaniyah: "IQ.SL",
    Wāsiţ: "IQ.WA",
  };