// Sample report data
import {
    FileSpreadsheet,
    FilePdf,
    File,
    FileJson,

} from "lucide-react";


export const reportData = [
    {
        id: 1,
        name: "Monthly Sales Report",
        category: "product",
        lastExported: "2025-03-15",
        formats: ["xlsx", "pdf", "csv"],
        size: "2.4 MB",
        scheduleEnabled: true,
        frequency: "Monthly",
        favorite: true,
    },
    {
        id: 2,
        name: "Inventory Status",
        category: "inventory",
        lastExported: "2025-03-20",
        formats: ["xlsx", "csv"],
        size: "4.1 MB",
        scheduleEnabled: false,
        frequency: null,
        favorite: true,
    },
    {
        id: 3,
        name: "Customer Segmentation Analysis",
        category: "customers",
        lastExported: "2025-03-10",
        formats: ["xlsx", "pdf", "json"],
        size: "3.7 MB",
        scheduleEnabled: true,
        frequency: "Weekly",
        favorite: false,
    },
    {
        id: 4,
        name: "Order Fulfillment Metrics",
        category: "order",
        lastExported: "2025-03-25",
        formats: ["xlsx", "csv"],
        size: "1.8 MB",
        scheduleEnabled: false,
        frequency: null,
        favorite: false,
    },
    {
        id: 5,
        name: "Product Performance Dashboard",
        category: "product",
        lastExported: "2025-03-18",
        formats: ["xlsx", "pdf", "csv", "json"],
        size: "5.2 MB",
        scheduleEnabled: true,
        frequency: "Daily",
        favorite: true,
    },
    {
        id: 6,
        name: "Inventory Aging Analysis",
        category: "inventory",
        lastExported: "2025-03-05",
        formats: ["xlsx", "csv"],
        size: "2.9 MB",
        scheduleEnabled: false,
        frequency: null,
        favorite: false,
    },
    {
        id: 7,
        name: "Customer Lifetime Value",
        category: "customers",
        lastExported: "2025-03-22",
        formats: ["xlsx", "pdf"],
        size: "3.3 MB",
        scheduleEnabled: true,
        frequency: "Monthly",
        favorite: true,
    },
    {
        id: 8,
        name: "Order Anomaly Detection",
        category: "order",
        lastExported: "2025-03-12",
        formats: ["xlsx", "json"],
        size: "1.5 MB",
        scheduleEnabled: false,
        frequency: null,
        favorite: false,
    },
];

// Export history data
export const exportHistoryData = [
    {
        id: 1,
        reportName: "Monthly Sales Report",
        exportedAt: "2025-03-15 09:30:45",
        format: "xlsx",
        size: "2.4 MB",
        status: "completed",
        exportedBy: "John Doe",
    },
    {
        id: 2,
        reportName: "Inventory Status",
        exportedAt: "2025-03-20 14:22:10",
        format: "csv",
        size: "4.1 MB",
        status: "completed",
        exportedBy: "John Doe",
    },
    {
        id: 3,
        reportName: "Customer Segmentation Analysis",
        exportedAt: "2025-03-10 11:15:33",
        format: "pdf",
        size: "3.7 MB",
        status: "completed",
        exportedBy: "Jane Smith",
    },
    {
        id: 4,
        reportName: "Monthly Sales Report",
        exportedAt: "2025-02-15 10:05:22",
        format: "xlsx",
        size: "2.3 MB",
        status: "completed",
        exportedBy: "John Doe",
    },
    {
        id: 5,
        reportName: "Product Performance Dashboard",
        exportedAt: "2025-03-18 16:40:12",
        format: "json",
        size: "5.2 MB",
        status: "completed",
        exportedBy: "Jane Smith",
    },
    {
        id: 6,
        reportName: "Inventory Aging Analysis",
        exportedAt: "2025-03-05 08:55:47",
        format: "xlsx",
        size: "2.9 MB",
        status: "completed",
        exportedBy: "John Doe",
    },
    {
        id: 7,
        reportName: "Order Fulfillment Metrics",
        exportedAt: "2025-03-26 09:12:30",
        format: "csv",
        size: "1.8 MB",
        status: "failed",
        exportedBy: "John Doe",
    },
    {
        id: 8,
        reportName: "Customer Lifetime Value",
        exportedAt: "2025-03-22 13:20:05",
        format: "pdf",
        size: "3.3 MB",
        status: "completed",
        exportedBy: "Jane Smith",
    },
    {
        id: 9,
        reportName: "Order Anomaly Detection",
        exportedAt: "2025-03-12 15:33:18",
        format: "json",
        size: "1.5 MB",
        status: "completed",
        exportedBy: "John Doe",
    },
    {
        id: 10,
        reportName: "Inventory Status",
        exportedAt: "2025-03-27 10:45:22",
        format: "xlsx",
        size: "4.2 MB",
        status: "in_progress",
        exportedBy: "Jane Smith",
    },
];

// Scheduled exports data
export const scheduledExportsData = [
    {
        id: 1,
        reportName: "Monthly Sales Report",
        frequency: "Monthly",
        nextExport: "2025-04-01 09:00:00",
        format: "xlsx",
        recipients: ["john@example.com", "sales@example.com"],
        status: "active",
    },
    {
        id: 2,
        reportName: "Product Performance Dashboard",
        frequency: "Daily",
        nextExport: "2025-03-31 08:00:00",
        format: "pdf",
        recipients: ["marketing@example.com"],
        status: "active",
    },
    {
        id: 3,
        reportName: "Customer Segmentation Analysis",
        frequency: "Weekly",
        nextExport: "2025-04-02 10:00:00",
        format: "xlsx",
        recipients: ["analytics@example.com", "marketing@example.com"],
        status: "active",
    },
    {
        id: 4,
        reportName: "Customer Lifetime Value",
        frequency: "Monthly",
        nextExport: "2025-04-15 09:00:00",
        format: "pdf",
        recipients: ["management@example.com"],
        status: "active",
    },
];

// Format options
export const formatOptions = [
    {
        value: "xlsx",
        label: "Excel (XLSX)",
        icon: <FileSpreadsheet size={16} />,
        description: "Microsoft Excel spreadsheet format",
    },
    {
        value: "csv",
        label: "CSV",
        icon: <File size={16} />,
        description: "Comma-separated values format",
    },
    {
        value: "pdf",
        label: "PDF",
        icon: <File size={16} />,
        description: "Portable Document Format",
    },
    {
        value: "json",
        label: "JSON",
        icon: <FileJson size={16} />,
        description: "JavaScript Object Notation format",
    },
];

// Frequency options
export const frequencyOptions = [
    { value: "daily", label: "Daily" },
    { value: "weekly", label: "Weekly" },
    { value: "monthly", label: "Monthly" },
    { value: "quarterly", label: "Quarterly" },
];
